version: '3.8'

services:
  backend:
    image: backend
    build:
      context: "./Main-back-end branch/spring-boot-rest-API/spring-boot-rest-API"
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    image: frontend
    build:
      context: "./Front-End/my-vue-app"
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
