version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: s3_project
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: "./Main back-end branch/spring-boot-rest-API/spring-boot-rest-API"
    container_name: backend
    command: ./mvnw spring-boot:run
    working_dir: /app
    volumes:
      - "./Main back-end branch/spring-boot-rest-API/spring-boot-rest-API:/app"
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
