version: '3.8'

services:
  main-backend:
    image: main-backend
    build:
      context: "./Main-back-end branch/spring-boot-rest-API/spring-boot-rest-API"
      dockerfile: Dockerfile
    container_name: main-backend
    ports:
      - "8080:8080"

  emailservice-backend:
    image: emailservice-backend
    build:
      context: "./Second-Back-End/EmailService"
      dockerfile: Dockerfile
    container_name: emailservice-backend
    ports:
      - "8081:8081"

  frontend:
    image: frontend
    build:
      context: "./Front-End/my-vue-app"
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
