name: Spring Boot CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17]  # Matrix for different Java versions (11, 17)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 for the latest checkout action

      # Step 2: Set up Java (from the matrix, it will set Java 11 or 17)
      - name: Set up JDK
        uses: actions/setup-java@v4  # Updated to v4 for the latest setup-java action
        with:
          java-version: ${{ matrix.java-version }}  # Dynamic Java version from the matrix
          distribution: 'temurin'  # You can also use 'zulu' or 'adopt'

      # Step 3: Cache Maven dependencies (updated to v4)
      - name: Cache Maven dependencies
        uses: actions/cache@v4  # Updated to v4 for the latest cache action
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project with Maven
      - name: Build with Maven
        run: mvn clean install --batch-mode -DskipTests=false

      # Step 5: Run tests with Maven
      - name: Run tests
        run: mvn test
