name: Spring Boot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11, 17]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Verify Java version
        run: java -version

      - name: Verify Maven version
        run: mvn -version

      - name: Build with Maven
        working-directory: "Main back-end branch/spring-boot-rest-API/spring-boot-rest-API"
        run: mvn clean install --batch-mode -DskipTests=false

      - name: Run tests
        working-directory: "Main back-end branch/spring-boot-rest-API/spring-boot-rest-API"
        run: mvn test
