name: CI with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Make mvnw executable
        run: chmod +x ./mvnw
        working-directory: ./Main back-end branch/spring-boot-rest-API/spring-boot-rest-API

      - name: Build and Run Containers
        run: docker-compose up -d --build
        working-directory: ./

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec s3-repo-vincevangestel_mysql_1 mysqladmin ping -h"localhost" --silent; do
            sleep 2
          done

      - name: Run tests inside backend container
        run: docker exec s3-repo-vincevangestel_backend_1 ./mvnw test
        working-directory: ./Main back-end branch/spring-boot-rest-API/spring-boot-rest-API

      - name: Tear down
        if: always()
        run: docker-compose down --remove-orphans
        working-directory: ./
