name: CI with Docker

on:
  push:
    branches: [main, Docker3]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build Docker images via Compose
        run: docker-compose -f docker-compose.yml build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push backend image
        run: |
          docker tag backend vgestel/backend:latest
          docker push vgestel/backend:latest

      - name: Tag and push frontend image
        run: |
          docker tag frontend vgestel/frontend:latest
          docker push vgestel/frontend:latest

      - name: Start backend and frontend services
        run: docker-compose -f docker-compose.yml up -d

      - name: Make mvnw executable
        run: chmod +x "./Main-back-end branch/spring-boot-rest-API/spring-boot-rest-API/mvnw"

      - name: Run backend tests with H2 (in-memory DB)
        run: |
          cd "./Main-back-end branch/spring-boot-rest-API/spring-boot-rest-API"
          ./mvnw clean test

      - name: Tear down services
        if: always()
        run: docker-compose -f docker-compose.yml down --remove-orphans
