name: CI with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Fix executable permission for mvnw
        run: chmod +x "./Main back-end branch/spring-boot-rest-API/spring-boot-rest-API/mvnw"

      - name: Build and Run Containers
        run: docker-compose up -d --build

      - name: Install mysql-client in backend
        run: docker exec backend apt-get update && docker exec backend apt-get install -y default-mysql-client

      - name: Show backend logs for debugging (if it fails)
        run: docker logs backend || true

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec backend mysqladmin ping -h"mysql" --silent; do
            sleep 2
          done

      - name: Run tests inside backend container
        run: docker exec backend ./mvnw test

      - name: Tear down
        if: always()
        run: docker-compose down --remove-orphans
