name: CI with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build Docker images via Compose
        run: docker-compose -f docker-compose.yml build

      - name: Start all services
        run: docker-compose -f docker-compose.yml up -d

      - name: Make mvnw executable
        run: chmod +x "./Main-back-end branch/spring-boot-rest-API/spring-boot-rest-API/mvnw"

      - name: Run backend tests with H2 (main-backend)
        run: |
          cd "./Main-back-end branch/spring-boot-rest-API/spring-boot-rest-API"
          ./mvnw clean test

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push main-backend image
        if: success()
        run: |
          docker tag main-backend vgestel/main-backend:latest
          docker push vgestel/main-backend:latest

      - name: Tag and push emailservice-backend image
        if: success()
        run: |
          docker tag emailservice-backend vgestel/emailservice-backend:latest
          docker push vgestel/emailservice-backend:latest

      - name: Tag and push frontend image
        if: success()
        run: |
          docker tag frontend vgestel/frontend:latest
          docker push vgestel/frontend:latest

      - name: Tear down services
        if: always()
        run: docker-compose -f docker-compose.yml down --remove-orphans
