name: CI with Docker

on:
  push:
    branches: [main, Docker2]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Make mvnw executable
        run: chmod +x "./Main-back-end branch/spring-boot-rest-API/spring-boot-rest-API/mvnw"

      - name: Start MySQL container
        run: docker-compose up -d mysql

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          until docker exec $(docker ps -qf "name=mysql") mysqladmin ping -h "localhost" --silent; do
            sleep 2
          done

      - name: Run tests
        run: |
          export SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/s3localdb
          export SPRING_DATASOURCE_USERNAME=root
          export SPRING_DATASOURCE_PASSWORD=root
          cd "./Main-back-end branch/spring-boot-rest-API/spring-boot-rest-API"
          ./mvnw test

      - name: Build Docker image
        run: docker build -t spring-boot-rest-api "./Main-back-end branch/spring-boot-rest-API/spring-boot-rest-API"

      - name: Tear down
        if: always()
        run: docker-compose down --remove-orphans
