name: CI with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and Run Containers
        run: docker-compose up -d --build
        working-directory: ./  # Adjust if docker-compose.yml is elsewhere

      - name: List running containers
        run: docker ps --format '{{.Names}}'

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec $(docker ps -qf "name=mysql") mysqladmin ping -h"mysql" --silent; do
            sleep 2
          done

      - name: Run tests inside backend container
        run: docker exec $(docker ps -qf "name=backend") ./mvnw test

      - name: Tear down
        if: always()
        run: docker-compose down --remove-orphans
        working-directory: ./
