name: CI with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make mvnw executable
        run: chmod +x ./mvnw
        working-directory: ./Main back-end branch/spring-boot-rest-API/spring-boot-rest-API

      - name: Run tests locally on runner
        run: ./mvnw test
        working-directory: ./Main back-end branch/spring-boot-rest-API/spring-boot-rest-API

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and Run Containers
        run: docker-compose up -d --build
        working-directory: ./ # Adjust if docker-compose.yml is in a subdirectory

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec $(docker ps -qf "name=mysql") mysqladmin ping -h"mysql" --silent; do
            sleep 2
          done

      - name: Tear down
        if: always()
        run: docker-compose down --remove-orphans
        working-directory: ./ # Adjust if needed
