name: CI with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run tests locally on runner
        working-directory: ./Main back-end branch/spring-boot-rest-API/spring-boot-rest-API
        run: ./mvnw test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Optional: Check if docker compose is available
      - name: Check Docker Compose version
        run: docker compose version

      - name: Build and Run Containers
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec $(docker ps -qf "name=mysql") mysqladmin ping -h"mysql" --silent; do
            sleep 2
          done

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.yml down --remove-orphans
